services:
  # Web service for the FastAPI application
  - type: web
    name: sentinel-intelligence-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SENTINEL_NOTIFICATION_EMAIL
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: CRON_SCHEDULE_TYPE
        value: production
      - key: SEND_TEST_NOTIFICATIONS
        value: false

  # Cron job service for scheduled intelligence gathering
  - type: cron
    name: sentinel-intelligence-cron
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python cron_scheduler.py
    schedule: "0 0 */3 * *"  # Every 3 days at midnight UTC
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SENTINEL_NOTIFICATION_EMAIL
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: CRON_SCHEDULE_TYPE
        value: production
      - key: SEND_TEST_NOTIFICATIONS
        value: false
